name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]

env:
  NODE_VERSION: 16.x

jobs:
  # 1 => Build and test the lambda source codes
  build-lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda/product-handler
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'lambda/product-handler/package-lock.json'
        
      - name: Install dependencies
        run: npm ci
      
      - name: Compile code
        run: npm run compile
      
      - name: Run tests
        run: npm run test

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda-code
          path: lambda/product-handler/build
          retention-days: 5

  
  # 2 => Build Infrastructure template
  build-cdk:
    runs-on: ubuntu-latest
    needs: build-lambda
    defaults:
      run:
        working-directory: cdk
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Download lambda code from build-lambda job
        uses: actions/download-artifact@v3
        with:
          name: lambda-code
          path: lambda/product-handler/build

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'cdk/package-lock.json'
        
      - name: Install dependencies
        run: npm ci

      #- run: npm run cdk bootstrap
      
      - name: Synthesize CloudFormation template
        run: npm run cdk synth

      #- run: npm run cdk deploy